### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by saulshanabrook** [metadsl/metadsl#55]

**Comment by rgommers** [comment]
Good idea. It's perhaps worth discussing that together in a call, and then adopting the same CoC for all Labs-driven projects?

**Comment by saulshanabrook** [comment]
Sure! This came up in preparation for the webinar on friday for uarray and metadsl with @hameerabbasi and I. 

I am happy to do adopt any one.

**Comment by hameerabbasi** [comment]
I’m happy to change mine, too.

**Comment by saulshanabrook** [comment]
This is done now.
