### ISSUE TITLE
TypeError: Cannot match concrete type <class '__main__.Number'> with hint <class 'int'>

### ISSUE THREAD

**Issue by xmnlab** [metadsl/metadsl#87]
hey @saulshanabrook, in my free time I am playing with metadsl to check if I can create an initial prototype for an Ibis alternative built on top of metadsl ... and found the follow problem:

`TypeError: Cannot match concrete type <class '__main__.Number'> with hint <class 'int'>` 

I created a gist with a complete and simple example: https://gist.github.com/xmnlab/6cf439181bd3e28a6cc5d4cd52d78a1d

it seems if `Number` has just `__add__` method it worked .. but with all the other magic method .. it is raising the error above.

any idea about that?

**Comment by saulshanabrook** [comment]
This looks like a bug! I'll take a look. Thanks for filing.

**Comment by dhirschfeld** [comment]
> *an Ibis alternative built on top of metadsl*

That sounds very interesting! :eyes:

**Comment by xmnlab** [comment]
it seems it is related to `__eq__` ... if I change to

```python
    @metadsl.expression
    def __eq__(self, other: Number) -> Number:
        """Define ``eq`` expression."""
``` 

it works ... not sure yet why ...

**Comment by saulshanabrook** [comment]
Ah @xmlab thank you! Yes that was it. You currently aren't allowed to override `__eq__` on metadsl expression, because we use that internally for some things. We should probably change this! But it makes testing easier right now.

So instead, I usually add a `eq` method to classes and use that.

**Comment by saulshanabrook** [comment]
Another thing is that isn't currently support for subclassing. So everything should just be a subclass of an Expression, not a sub-subclass. So `Integer` shouldn't subclass from `Number`.

If you have questions about this, happy to go more in depth. It might be most useful with an example though, if you that does come up in what you are doing.

**Comment by xmnlab** [comment]
@saulshanabrook thanks for the feedback! I will keep it in mind! thank you so much!

**Comment by saulshanabrook** [comment]
Closing for now. Eventually we want to re-work the equality.
